//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyBank.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class moneybankEntities : DbContext
    {  
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblbank> tblbanks { get; set; }
        public virtual DbSet<tblexpense> tblexpenses { get; set; }
        public virtual DbSet<tblexpensedetail> tblexpensedetails { get; set; }
        public virtual DbSet<tblexpensetype> tblexpensetypes { get; set; }
        public virtual DbSet<tbllog> tbllogs { get; set; }
        public virtual DbSet<tblreceive> tblreceives { get; set; }
        public virtual DbSet<tblreceivedetail> tblreceivedetails { get; set; }
        public virtual DbSet<tblreceivetype> tblreceivetypes { get; set; }
        public virtual DbSet<tblreconcile> tblreconciles { get; set; }
        public virtual DbSet<tbltransaction> tbltransactions { get; set; }
        public virtual DbSet<tbluser> tblusers { get; set; }
        public virtual DbSet<tbluserbank> tbluserbanks { get; set; }
        public virtual DbSet<tbluserbankaccount> tbluserbankaccounts { get; set; }
        public virtual DbSet<tbluserinformation> tbluserinformations { get; set; }
    }
}
