//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyBank.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblbank
    {
        public int IdTrack { get; set; }
        public Nullable<System.DateTime> DateReference { get; set; }
        public string BankName { get; set; }
        public string BankSwiftcode { get; set; }
        public string BankLocation { get; set; }
        public string BankProvider { get; set; }
    }
}
