//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyBank.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblexpensedetail
    {
        public int IdTrack { get; set; }
        public Nullable<System.DateTime> DateReference { get; set; }
        public string ExpenseTransNo { get; set; }
        public string ExpenseName { get; set; }
        public Nullable<decimal> ExpenseAmount { get; set; }
        public Nullable<int> ExpenseQuantity { get; set; }
        public string Remarks { get; set; }
        public decimal ExpenseTotal { get; set; }
    
        public virtual tblexpense tblexpense { get; set; }
    }
}
