//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyBank.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblexpensedetail
    {
        public int IdTrack { get; set; }
        public string TransNo { get; set; }
        public string Description { get; set; }
        public decimal Amount { get; set; }
        public int Qty { get; set; }
        public decimal Price { get; set; }
        public string ExpenseType { get; set; }
    
        public virtual tblexpense tblexpense { get; set; }
    }
}
