//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyBank.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblexpense
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblexpense()
        {
            this.tblexpensedetails = new HashSet<tblexpensedetail>();
        }
    
        public Nullable<System.DateTime> DateReference { get; set; }
        public string UserID { get; set; }
        public string ExpenseTransNo { get; set; }
        public string BankAccountNo { get; set; }
        public Nullable<decimal> TotalExpenseAmount { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblexpensedetail> tblexpensedetails { get; set; }
    }
}
