//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyBank.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblreceivedetail
    {
        public int IdTrack { get; set; }
        public Nullable<System.DateTime> DateReference { get; set; }
        public string ReceiveTransNo { get; set; }
        public string ReceiveItemName { get; set; }
        public Nullable<decimal> ReceiveAmount { get; set; }
        public Nullable<int> ReceiveQuantity { get; set; }
        public string Remarks { get; set; }
        public decimal ReceiveAmountTotal { get; set; }
    
        public virtual tblreceive tblreceive { get; set; }
    }
}
