//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyBank.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblreceive
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblreceive()
        {
            this.tblreceivedetails = new HashSet<tblreceivedetail>();
        }
    
        public Nullable<System.DateTime> DateReference { get; set; }
        public string ReceiveTransNo { get; set; }
        public string UserID { get; set; }
        public string BankAccountNo { get; set; }
        public Nullable<decimal> TotalReceiveAmount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblreceivedetail> tblreceivedetails { get; set; }
    }
}
