//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyBank.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblreconcile
    {
        public int IdTrack { get; set; }
        public Nullable<System.DateTime> DateReference { get; set; }
        public string UserID { get; set; }
        public string BankAccountNo { get; set; }
        public Nullable<decimal> BeginingBalance { get; set; }
        public Nullable<decimal> EndingBalance { get; set; }
        public string Remarks { get; set; }
        public string TransNo { get; set; }
        public string ReferenceTransNo { get; set; }
        public string Status { get; set; }
    }
}
