//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyBank.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbltransaction
    {
        public long IdTrack { get; set; }
        public string TransNo { get; set; }
        public string ReferenceTransNo { get; set; }
        public string BankAccountNo { get; set; }
        public string Description { get; set; }
        public decimal Added { get; set; }
        public decimal Deducted { get; set; }
        public decimal OldBalance { get; set; }
        public decimal NewBalance { get; set; }
        public string Remarks { get; set; }
        public System.DateTime DateReference { get; set; }
        public string UserID { get; set; }
    }
}
