//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyBank.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbluser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbluser()
        {
            this.tbluserbanks = new HashSet<tbluserbank>();
            this.tbluserbankaccounts = new HashSet<tbluserbankaccount>();
            this.tbluserinformations = new HashSet<tbluserinformation>();
        }
    
        public Nullable<System.DateTime> DateReference { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> DateLastLogin { get; set; }
        public string UserLevel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbluserbank> tbluserbanks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbluserbankaccount> tbluserbankaccounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbluserinformation> tbluserinformations { get; set; }
    }
}
