//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyBank.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblversion
    {
        public long IdTrack { get; set; }
        public string NewUpdates { get; set; }
        public string OldUpdates { get; set; }
        public string Version { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
    }
}
